"use client";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, Quote } from "lucide-react";
import { motion, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { useRef } from "react";
import type { Property, Settings } from "@/lib/types";
import { CountUp, ImageReveal, ParallaxImage, Reveal } from "@/components/motion";
import PropertyCard from "@/components/property-card";

export function Hero({ settings }: { settings: Settings }) { const reduced = useReducedMotion(); return <section className="relative flex min-h-[100dvh] items-end overflow-hidden bg-navy pt-24 text-cream"><ParallaxImage src={settings.hero.image} alt="Architectural residence" /><div className="absolute inset-0 bg-gradient-to-t from-[#0a0f1a]/85 via-[#0a0f1a]/25 to-[#0a0f1a]/20" /><div className="wrap relative z-10 pb-14 md:pb-20"><motion.p initial={reduced ? false : { opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .25 }} className="eyebrow text-[#e3b85c]">Ahmedabad · Gandhinagar</motion.p><h1 className="display mt-5 max-w-5xl text-balance text-[clamp(3.6rem,9vw,8.6rem)] leading-[.8]">{settings.hero.headline.split(" ").map((word, i) => <motion.span className="mr-[.18em] inline-block" initial={reduced ? false : { y: 120, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: .3 + i * .06, duration: .85, ease: [0.22, 1, .36, 1] }} key={word + i}>{word}</motion.span>)}</h1><div className="mt-9 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><p className="max-w-md text-sm leading-6 text-white/80 md:text-base">{settings.hero.subheadline}</p><Link href="/properties" className="group inline-flex w-fit items-center gap-4 border-b border-gold pb-2 text-sm font-semibold text-gold">View the collection <ArrowRight size={17} className="transition-transform group-hover:translate-x-1" /></Link></div></div><div className="absolute bottom-5 right-6 z-10 text-[.6rem] font-bold uppercase tracking-[.18em] text-white/50">Scroll to explore</div></section>; }

export function Intro({ settings }: { settings: Settings }) { return <section className="bg-cream py-24 md:py-36"><div className="wrap grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><Reveal><p className="eyebrow">{settings.about.eyebrow}</p><div className="gold-rule mt-5" /></Reveal><Reveal delay={.1}><h2 className="display max-w-3xl text-balance text-5xl leading-[.9] text-navy md:text-7xl">{settings.about.heading}</h2><p className="mt-8 max-w-xl leading-7 text-navy/70">{settings.about.text}</p><Link href="/about" className="mt-9 inline-flex items-center gap-3 text-sm font-bold text-navy">More about us <ArrowUpRight size={16} className="text-gold" /></Link></Reveal></div></section>; }

export function FeaturedGallery({ properties }: { properties: Property[] }) { const ref = useRef<HTMLElement>(null); const { scrollYProgress } = useScroll({ target: ref, offset: ["start start", "end end"] }); const x = useTransform(scrollYProgress, [0, 1], ["0%", "-48%"]); return <section ref={ref} className="hidden h-[260vh] bg-navy lg:block"><div className="sticky top-0 flex h-screen items-center overflow-hidden"><div className="wrap absolute top-14 z-10"><p className="eyebrow">A selected collection</p><h2 className="display mt-3 text-6xl text-cream">The places with a point of view.</h2></div><motion.div style={{ x }} className="flex gap-7 pl-[calc((100vw-82rem)/2)] pt-32">{properties.map((property) => <Link href={`/properties/${property.slug}`} key={property.id} className="group relative block w-[39rem] shrink-0 overflow-hidden"><img src={property.images[0]} alt={property.title} className="h-[29rem] w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/75 to-transparent p-7 text-cream"><p className="eyebrow">{property.type} · {property.locality}</p><h3 className="display mt-2 text-4xl">{property.title}</h3></div></Link>)}</motion.div></div></section>; }
export function MobileFeatured({ properties }: { properties: Property[] }) { return <section className="bg-navy py-20 lg:hidden"><div className="wrap"><p className="eyebrow">A selected collection</p><h2 className="display mt-3 text-5xl leading-none text-cream">The places with a point of view.</h2><div className="mt-9 flex snap-x gap-4 overflow-x-auto pb-4">{properties.map((p) => <Link href={`/properties/${p.slug}`} key={p.id} className="relative aspect-[.8] w-[78vw] shrink-0 snap-center overflow-hidden"><img src={p.images[0]} alt={p.title} className="h-full w-full object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 p-5"><h3 className="display text-3xl text-cream">{p.title}</h3></div></Link>)}</div></div></section>; }
export function PropertyTypes({ settings, properties }: { settings: Settings; properties: Property[] }) { const imageFor = (type: string) => properties.find((p) => p.type === type)?.images[0] || settings.about.image; return <section className="py-24"><div className="wrap"><Reveal><p className="eyebrow">Find your fit</p><h2 className="display mt-3 text-5xl text-navy md:text-6xl">A collection for every chapter.</h2></Reveal><div className="mt-10 grid gap-px bg-navy/15 sm:grid-cols-2 lg:grid-cols-5">{settings.propertyTypes.map((type) => <Link className="group relative aspect-[.92] overflow-hidden bg-navy" href={`/properties?type=${encodeURIComponent(type)}`} key={type}><img src={imageFor(type)} alt="" className="h-full w-full object-cover opacity-60 transition duration-700 group-hover:scale-110 group-hover:opacity-80"/><div className="absolute inset-0 flex items-end justify-between p-5 text-cream"><span className="display text-3xl">{type}s</span><ArrowUpRight className="text-gold"/></div></Link>)}</div></div></section>; }
export function Stats({ settings }: { settings: Settings }) { return <section className="bg-navy py-20 text-cream"><div className="wrap grid gap-10 sm:grid-cols-2 lg:grid-cols-4">{settings.stats.map((stat) => <Reveal key={stat.label}><p className="display text-6xl text-gold"><CountUp value={stat.value}/><sup className="text-3xl">+</sup></p><p className="mt-2 text-sm text-white/65">{stat.label}</p></Reveal>)}</div></section>; }
export function WhyChooseUs() { const reasons = ["A quietly rigorous edit of the market", "Deep local relationships and off-market access", "Honest advice at every stage of your decision", "A team that stays present after the keys change hands"]; return <section className="bg-cream py-24 md:py-36"><div className="wrap grid gap-14 lg:grid-cols-[.9fr_1.1fr]"><Reveal><p className="eyebrow">The TDS approach</p><h2 className="display mt-4 text-6xl leading-[.86] text-navy">Knowledge is useful. Care is essential.</h2></Reveal><div className="divide-y divide-navy/15">{reasons.map((reason, index) => <Reveal delay={index * .06} key={reason}><div className="flex gap-5 py-6"><span className="display text-2xl text-gold">0{index + 1}</span><p className="pt-1 text-lg text-navy">{reason}</p></div></Reveal>)}</div></div></section>; }
export function Testimonials({ settings }: { settings: Settings }) { return <section className="bg-[#e8e4dc] py-24"><div className="wrap"><p className="eyebrow">Kind words</p><div className="mt-10 grid gap-5 lg:grid-cols-3">{settings.testimonials.map((item, i) => <Reveal delay={i * .08} key={item.name}><article className="h-full bg-cream p-7"><Quote className="text-gold"/><blockquote className="display mt-9 text-3xl leading-[.95] text-navy">“{item.quote}”</blockquote><p className="mt-9 text-sm font-bold">{item.name}</p><p className="mt-1 text-xs text-navy/55">{item.role}</p></article></Reveal>)}</div></div></section>; }
export function Marquee({ settings }: { settings: Settings }) { const words = [...settings.localities, "Ahmedabad", "Gandhinagar"]; return <section className="overflow-hidden border-y border-navy/15 bg-cream py-5"><motion.div className="flex w-max gap-10 whitespace-nowrap" animate={{ x: ["0%", "-50%"] }} transition={{ repeat: Infinity, duration: 24, ease: "linear" }}>{[...words, ...words, ...words, ...words].map((word, i) => <span className="display text-3xl text-navy/35" key={i}>{word} <b className="ml-8 text-gold">✦</b></span>)}</motion.div></section>; }
export function FinalCta({ settings }: { settings: Settings }) { return <section className="bg-gold py-20"><div className="wrap flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow text-navy">Your next chapter</p><h2 className="display mt-3 max-w-3xl text-6xl leading-[.85] text-navy">Let’s find a place that feels like yours.</h2></div><Link href="/contact" className="inline-flex w-fit items-center gap-4 bg-navy px-6 py-4 text-sm font-bold text-cream">Talk to TDS <ArrowRight size={17}/></Link></div></section>; }
