"use client";
import { useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Grid2X2, List, Search, SlidersHorizontal, X } from "lucide-react";
import type { Property, Settings } from "@/lib/types";
import PropertyCard from "@/components/property-card";
import { propertyPrice } from "@/lib/format";

export default function PropertyFilters({ properties, settings }: { properties: Property[]; settings: Settings }) { const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const [sheet, setSheet] = useState(false); const [layout, setLayout] = useState<"grid" | "list">("grid"); const [search, setSearch] = useState(params.get("q") || ""); const initial = { type: params.get("type") || "", status: params.get("status") || "", city: params.get("city") || "", beds: params.get("beds") || "", max: params.get("max") || "", sort: params.get("sort") || "newest" }; const [filters, setFilters] = useState(initial);
  const update = (key: keyof typeof filters, value: string) => { const next = { ...filters, [key]: value }; setFilters(next); const q = new URLSearchParams(); Object.entries(next).forEach(([k, v]) => v && q.set(k, v)); if (search) q.set("q", search); router.replace(`${pathname}?${q.toString()}`, { scroll: false }); };
  const result = useMemo(() => properties.filter((p) => (!filters.type || p.type === filters.type) && (!filters.status || p.status === filters.status) && (!filters.city || p.city === filters.city) && (!filters.beds || p.bedrooms >= Number(filters.beds)) && (!filters.max || p.price <= Number(filters.max)) && (!search || `${p.title} ${p.locality} ${p.city}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b) => filters.sort === "price-low" ? a.price-b.price : filters.sort === "price-high" ? b.price-a.price : a.title.localeCompare(b.title)), [properties, filters, search]);
  const controls = <><label className="relative block"><Search className="absolute left-3 top-3.5 text-navy/45" size={16}/><input value={search} onChange={(e) => { setSearch(e.target.value); const q = new URLSearchParams(params.toString()); e.target.value ? q.set("q", e.target.value) : q.delete("q"); router.replace(`${pathname}?${q}`, { scroll: false }); }} className="field pl-10" placeholder="Search by area or property" /></label><Select value={filters.type} onChange={(v) => update("type",v)} label="All types" values={settings.propertyTypes}/><Select value={filters.status} onChange={(v) => update("status",v)} label="All statuses" values={["For Sale","For Rent","Sold","Under Construction"]}/><Select value={filters.city} onChange={(v) => update("city",v)} label="All cities" values={[...new Set(properties.map(p=>p.city))]}/><Select value={filters.beds} onChange={(v) => update("beds",v)} label="Any beds" values={["1","2","3","4","5"]} suffix="+ beds"/><Select value={filters.max} onChange={(v) => update("max",v)} label="Any price" values={["10000000","25000000","50000000","100000000"]} formatter={(v)=>`Up to ${propertyPrice({price:Number(v),currency:"INR"})}`}/></>;
  return <><div className="mt-9 hidden gap-3 lg:grid lg:grid-cols-3 xl:grid-cols-6">{controls}</div><div className="mt-7 flex items-center justify-between"><p className="text-sm text-navy/60"><b className="text-navy">{result.length}</b> properties found</p><div className="flex items-center gap-2"><button onClick={() => setSheet(true)} className="inline-flex min-h-11 items-center gap-2 border border-navy/20 px-3 text-sm lg:hidden"><SlidersHorizontal size={16}/> Filters</button><Select value={filters.sort} onChange={(v)=>update("sort",v)} label="Sort" values={["newest","price-low","price-high"]} labels={{newest:"Newest", "price-low":"Price: low to high", "price-high":"Price: high to low"}}/><div className="hidden border border-navy/20 sm:flex"><button aria-label="Grid view" onClick={()=>setLayout("grid")} className={`grid h-10 w-10 place-items-center ${layout==="grid" ? "bg-navy text-cream" : ""}`}><Grid2X2 size={16}/></button><button aria-label="List view" onClick={()=>setLayout("list")} className={`grid h-10 w-10 place-items-center ${layout==="list" ? "bg-navy text-cream" : ""}`}><List size={16}/></button></div></div></div><div className={layout === "grid" ? "mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3" : "mt-8 grid gap-5"}>{result.map((property, i) => layout === "grid" ? <PropertyCard property={property} priority={i<3} key={property.id}/> : <ListCard key={property.id} property={property}/>)}</div>{!result.length && <div className="mt-12 border border-dashed border-navy/25 px-6 py-16 text-center"><p className="display text-4xl text-navy">No exact matches just yet.</p><button onClick={() => { setFilters({type:"",status:"",city:"",beds:"",max:"",sort:"newest"}); setSearch(""); router.replace(pathname); }} className="mt-4 text-sm font-bold text-gold">Clear filters</button></div>} {sheet && <div className="fixed inset-0 z-[100] bg-ink/45 lg:hidden"><div className="absolute inset-x-0 bottom-0 max-h-[85dvh] overflow-auto bg-cream p-6"><div className="flex items-center justify-between"><h2 className="display text-3xl text-navy">Refine collection</h2><button aria-label="Close filters" onClick={()=>setSheet(false)}><X/></button></div><div className="mt-6 grid gap-3">{controls}</div><button onClick={()=>setSheet(false)} className="mt-6 w-full bg-navy py-4 text-sm font-bold text-cream">Show {result.length} properties</button></div></div>}</>;
}
function Select({ value, onChange, label, values, suffix = "", formatter, labels }: {value:string;onChange:(v:string)=>void;label:string;values:string[];suffix?:string;formatter?:(v:string)=>string;labels?:Record<string,string>}) { return <select aria-label={label} className="field bg-white" value={value} onChange={(e)=>onChange(e.target.value)}><option value="">{label}</option>{values.map((value)=><option key={value} value={value}>{labels?.[value] || formatter?.(value) || `${value}${suffix}`}</option>)}</select>; }
function ListCard({ property }: { property: Property }) { return <a href={`/properties/${property.slug}`} className="group grid overflow-hidden bg-white shadow-card md:grid-cols-[18rem_1fr]"><img src={property.images[0]} alt={property.title} className="aspect-video h-full w-full object-cover md:aspect-auto"/><div className="p-6"><p className="eyebrow">{property.type} · {property.locality}</p><h3 className="display mt-2 text-4xl text-navy">{property.title}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-navy/65">{property.shortDescription}</p><p className="mt-5 font-bold text-navy">{propertyPrice(property)}</p></div></a>; }
